/**
 * Generate the extension icon.
 *
 * Committed as a PNG, generated by this script so the artwork is reviewable as
 * code rather than as an opaque binary someone is afraid to touch.
 *
 * The image is the tab's own idea, shrunk: a severity rail down the left edge
 * whose segments are ordered most-dangerous-first, with the rows beside it. At
 * 128px nothing else survives, and this at least says "ranked list of changes"
 * rather than "generic cloud".
 *
 *   node scripts/make-icon.mjs
 */
import { deflateSync } from 'node:zlib';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const SIZE = 128;
const BG = [0x16, 0x1c, 0x23];

/** Straight from the tab's severity tones, most dangerous first. */
const RAIL = [
  [0xf8, 0x51, 0x49], // destructive
  [0xb6, 0x9b, 0xe0], // protectionLoss
  [0x4a, 0xc7, 0x7c], // create
  [0xf2, 0xc9, 0x4c], // modify
  [0x8b, 0x94, 0x9e], // unevaluated
];

/** Row lengths, in the same order. Uneven on purpose — a real run is uneven. */
const ROWS = [0.42, 0.66, 0.9, 0.78, 0.5];

const raster = Buffer.alloc(SIZE * SIZE * 3);
for (let i = 0; i < SIZE * SIZE; i += 1) {
  raster[i * 3] = BG[0];
  raster[i * 3 + 1] = BG[1];
  raster[i * 3 + 2] = BG[2];
}

function fill(x0, y0, w, h, [r, g, b]) {
  for (let y = y0; y < y0 + h; y += 1) {
    if (y < 0 || y >= SIZE) continue;
    for (let x = x0; x < x0 + w; x += 1) {
      if (x < 0 || x >= SIZE) continue;
      const i = (y * SIZE + x) * 3;
      raster[i] = r;
      raster[i + 1] = g;
      raster[i + 2] = b;
    }
  }
}

const TOP = 18;
const BAND = 19;
const RAIL_X = 18;
const RAIL_W = 6;
const ROW_X = 34;
const ROW_H = 9;

for (let i = 0; i < RAIL.length; i += 1) {
  const y = TOP + i * BAND;
  // The rail runs edge to edge within its band, so same-rung rows read as one
  // contiguous block — the property that makes it a histogram.
  fill(RAIL_X, y, RAIL_W, BAND - 3, RAIL[i]);
  // The row itself, dimmer: the rail carries the colour, the row carries length.
  const width = Math.round((SIZE - ROW_X - 18) * ROWS[i]);
  const [r, g, b] = RAIL[i];
  fill(ROW_X, y + 2, width, ROW_H, [
    Math.round(r * 0.45 + BG[0] * 0.55),
    Math.round(g * 0.45 + BG[1] * 0.55),
    Math.round(b * 0.45 + BG[2] * 0.55),
  ]);
}

// PNG: 8-bit truecolour, one filter byte (0 = None) per scanline.
const scanlines = Buffer.alloc(SIZE * (SIZE * 3 + 1));
for (let y = 0; y < SIZE; y += 1) {
  scanlines[y * (SIZE * 3 + 1)] = 0;
  raster.copy(scanlines, y * (SIZE * 3 + 1) + 1, y * SIZE * 3, (y + 1) * SIZE * 3);
}

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buf) {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(SIZE, 0);
ihdr.writeUInt32BE(SIZE, 4);
ihdr[8] = 8; // bit depth
ihdr[9] = 2; // colour type: truecolour
const png = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  chunk('IHDR', ihdr),
  chunk('IDAT', deflateSync(scanlines, { level: 9 })),
  chunk('IEND', Buffer.alloc(0)),
]);

const out = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'images',
  'extension-icon.png',
);
await fs.writeFile(out, png);
console.log(`${out} — ${SIZE}x${SIZE}, ${png.length} bytes`);
